In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from glob import glob
#stock_files = sorted(glob('data/stocks*.csv'))
#df=pd.read_csv(r'D:\Documents\Projects\VAERS\2020VAERSData.csv')
#files=glob(r'D:\Documents\Projects\VAERS\1990*.csv')
#files
data=glob(r'D:\Documents\Projects\VAERS\*DATA.csv')
sympt=glob(r'D:\Documents\Projects\VAERS\*SYMPTOMS.csv')
vax=glob(r'D:\Documents\Projects\VAERS\*VAX.csv')

data_list=[data,sympt,vax]

In [ ]:
#encoding='cp1252'  is used to overcome read error

data_df = pd.DataFrame([])
for file in data:
    temp_df=pd.read_csv(file,encoding='cp1252',low_memory=False)
    data_df=pd.concat([data_df,temp_df], ignore_index=True)
#del temp_df

sympt_df = pd.DataFrame([])
for file in sympt:
    temp_df=pd.read_csv(file,encoding='cp1252',low_memory=False)
    sympt_df=pd.concat([sympt_df,temp_df], ignore_index=True)
#del temp_df

vax_df = pd.DataFrame([])
for file in vax:
    temp_df=pd.read_csv(file,encoding='cp1252',low_memory=False)
    vax_df=pd.concat([vax_df,temp_df], ignore_index=True)
#del temp_df

In [ ]:
data_df.to_csv('D:\Documents\Projects\VAERS\data.csv')

In [ ]:
sympt_df.to_csv('D:\Documents\Projects\VAERS\symptoms.csv')

In [ ]:
vax_df.to_csv(r'D:\Documents\Projects\VAERS\vax.csv',mode='w')

In [ ]:
display(data_df.head(), sympt_df.head(),vax_df.head())

In [7]:
data_df=pd.read_csv(r'D:\Documents\Projects\VAERS\data.csv',low_memory=False)
sympt_df=pd.read_csv(r'D:\Documents\Projects\VAERS\symptoms.csv',low_memory=False)
vax_df=pd.read_csv(r'D:\Documents\Projects\VAERS\vax.csv',low_memory=False)

In [ ]:
print(len(sympt_df.VAERS_ID.unique()))
print(len(sympt_df))

In [8]:
sympt_df=sympt_df.drop(['SYMPTOMVERSION1','SYMPTOMVERSION2','SYMPTOMVERSION3','SYMPTOMVERSION4','SYMPTOMVERSION5','Unnamed: 0.1','Unnamed: 0'],axis=1)

In [ ]:
sympt_df=sympt_df.fillna(' ')

In [ ]:
sympt_df['SYMPTOMS']=sympt_df[['SYMPTOM1','SYMPTOM2','SYMPTOM3','SYMPTOM4','SYMPTOM5',]].agg(' '.join,axis=1)
sympt_df['SYMPTOMS']=sympt_df['SYMPTOMS'].str.strip()
sympt_df['SYMPTOMS']=sympt_df['SYMPTOMS'].str.replace(' ',', ')
sympt_df

In [ ]:
sympt=sympt_df.drop(sympt_df.columns[[1,2,3,4,5]],axis=1)

In [ ]:
sypmt=sympt.groupby('VAERS_ID')['SYMPTOMS'].apply(', '.join).reset_index()

In [10]:
vax_df.head()

,Unnamed: 0,VAERS_ID,VAX_TYPE,VAX_MANU,VAX_LOT,VAX_DOSE_SERIES,VAX_ROUTE,VAX_SITE,VAX_NAME
0,0,25001,DTP,CONNAUGHT LABORATORIES,9Q01042,UNK,IM,NaN,DTP (NO BRAND NAME)
1,1,25003,DTP,LEDERLE LABORATORIES,259962,4,IM,NaN,DTP (TRI-IMMUNOL)
2,2,25003,OPV,PFIZER\WYETH,241950,4,PO,MO,"POLIO VIRUS, ORAL (ORIMUNE)"
3,3,25004,OPV,PFIZER\WYETH,232961,UNK,NaN,NaN,"POLIO VIRUS, ORAL (ORIMUNE)"
4,4,25005,TD,LEDERLE LABORATORIES,247955,UNK,IM,NaN,TD ADSORBED (NO BRAND NAME)

In [12]:
vax=vax_df.drop(vax_df.columns[[0,4,5,6,7,8]],axis=1)

In [13]:
vax.head()

   VAERS_ID VAX_TYPE                VAX_MANU
0     25001      DTP  CONNAUGHT LABORATORIES
1     25003      DTP    LEDERLE LABORATORIES
2     25003      OPV            PFIZER\WYETH
3     25004      OPV            PFIZER\WYETH
4     25005       TD    LEDERLE LABORATORIES

In [14]:
data_df.head()

,Unnamed: 0,VAERS_ID,RECVDATE,STATE,AGE_YRS,CAGE_YR,CAGE_MO,SEX,RPT_DATE,SYMPTOM_TEXT,...,HISTORY,PRIOR_VAX,SPLTTYPE,FORM_VERS,TODAYS_DATE,BIRTH_DEFECT,OFC_VISIT,ER_ED_VISIT,ALLERGIES,Unnamed: 0.1
0,0,25001.0,07/02/1990,WI,0.2,NaN,NaN,F,NaN,Loud intense cry with screaming for 1 1/2 hrs....,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
1,1,25003.0,07/02/1990,TX,0.8,NaN,NaN,M,NaN,"Hypotonic, Hyporesponsive episode, Infant died...",...,NaN,~ ()~~~In patient,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
2,2,25004.0,07/02/1990,NY,0.9,NaN,NaN,M,NaN,"Pt developed chills for approx. 1 hr, felt ach...",...,NaN,~ ()~~~In patient,890269201,1.0,NaN,NaN,NaN,NaN,NaN,NaN
3,3,25005.0,07/02/1990,OK,NaN,NaN,NaN,U,NaN,7 patients within 2 weeks have reported joint ...,...,NaN,~ ()~~~In patient,890277901,1.0,NaN,NaN,NaN,NaN,NaN,NaN
4,4,25006.0,07/02/1990,OH,16.0,16.0,NaN,F,NaN,16 yr old female feeling faint & then had seiz...,...,no hx of local or systemic rxns,~ ()~~~In patient,890278001,1.0,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
data=data_df.drop(data_df.columns[[0,5,6,8,12,13,14,15,16,17,18,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36]],axis=1)

In [23]:
data.head()

,VAERS_ID,RECVDATE,STATE,AGE_YRS,SEX,SYMPTOM_TEXT,DIED,DATEDIED,VAX_DATE,ONSET_DATE,NUMDAYS
0,25001.0,07/02/1990,WI,0.2,F,Loud intense cry with screaming for 1 1/2 hrs....,NaN,NaN,06/04/1990,06/04/1990,0.0
1,25003.0,07/02/1990,TX,0.8,M,"Hypotonic, Hyporesponsive episode, Infant died...",Y,NaN,01/29/1990,02/04/1990,6.0
2,25004.0,07/02/1990,NY,0.9,M,"Pt developed chills for approx. 1 hr, felt ach...",NaN,NaN,11/13/1989,11/13/1989,0.0
3,25005.0,07/02/1990,OK,NaN,U,7 patients within 2 weeks have reported joint ...,NaN,NaN,NaN,NaN,NaN
4,25006.0,07/02/1990,OH,16.0,F,16 yr old female feeling faint & then had seiz...,NaN,NaN,11/17/1989,11/17/1989,0.0

In [25]:
import functools

In [28]:
vaers=pd.merge(data, sympt_df, on=['VAERS_ID'],how='left')
vaers=pd.merge(vaers, vax, on=['VAERS_ID'],how='left')

In [29]:
vaers.head()

,VAERS_ID,RECVDATE,STATE,AGE_YRS,SEX,SYMPTOM_TEXT,DIED,DATEDIED,VAX_DATE,ONSET_DATE,NUMDAYS,SYMPTOM1,SYMPTOM2,SYMPTOM3,SYMPTOM4,SYMPTOM5,VAX_TYPE,VAX_MANU
0,25001.0,07/02/1990,WI,0.2,F,Loud intense cry with screaming for 1 1/2 hrs....,NaN,NaN,06/04/1990,06/04/1990,0.0,Agitation,NaN,NaN,NaN,NaN,DTP,CONNAUGHT LABORATORIES
1,25003.0,07/02/1990,TX,0.8,M,"Hypotonic, Hyporesponsive episode, Infant died...",Y,NaN,01/29/1990,02/04/1990,6.0,Delirium,Hypokinesia,Hypotonia,NaN,NaN,DTP,LEDERLE LABORATORIES
2,25003.0,07/02/1990,TX,0.8,M,"Hypotonic, Hyporesponsive episode, Infant died...",Y,NaN,01/29/1990,02/04/1990,6.0,Delirium,Hypokinesia,Hypotonia,NaN,NaN,OPV,PFIZER\WYETH
3,25004.0,07/02/1990,NY,0.9,M,"Pt developed chills for approx. 1 hr, felt ach...",NaN,NaN,11/13/1989,11/13/1989,0.0,Chills,Dermatitis contact,Oedema genital,Pelvic pain,NaN,OPV,PFIZER\WYETH
4,25005.0,07/02/1990,OK,NaN,U,7 patients within 2 weeks have reported joint ...,NaN,NaN,NaN,NaN,NaN,Arthritis,Injection site oedema,Injection site reaction,NaN,NaN,TD,LEDERLE LABORATORIES

In [31]:
vaers.to_csv(r'D:\Documents\Projects\VAERS\vaers.csv')

In [ ]:
vaers=pd.read_csv(r'D:\Documents\Projects\VAERS\vaers.csv')

In [61]:
vaers['RECVDATE']=vaers.RECVDATE.fillna('01/01/1900')
vaers['DATEDIED']=vaers.DATEDIED.fillna('01/01/1900')
vaers['VAX_DATE']=vaers.VAX_DATE.fillna('01/01/1900')
vaers['ONSET_DATE']=vaers.ONSET_DATE.fillna('01/01/1900')
vaers['STATE']=vaers.STATE.fillna('UKNOWN')
vaers['SEX']=vaers.SEX.fillna('U')
vaers['DIED']=vaers.DIED.fillna('UKNOWN')
vaers['VAX_TYPE']=vaers.VAX_TYPE.fillna('UKNOWN')
vaers['VAX_MANU']=vaers.VAX_MANU.fillna('UKNOWN')
vaers['NUMDAYS']=vaers.NUMDAYS.fillna('0')
vaers['AGE_YRS']=vaers.AGE_YRS.fillna('100')

In [62]:
vaers.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2212158 entries, 0 to 2212157
Data columns (total 18 columns):
 #   Column        Dtype
---  ------        -----
 0   VAERS_ID      int32
 1   RECVDATE      datetime64[ns]
 2   STATE         object
 3   AGE_YRS       float64
 4   SEX           object
 5   SYMPTOM_TEXT  object
 6   DIED          object
 7   DATEDIED      datetime64[ns]
 8   VAX_DATE      datetime64[ns]
 9   ONSET_DATE    datetime64[ns]
 10  NUMDAYS       float64
 11  SYMPTOM1      object
 12  SYMPTOM2      object
 13  SYMPTOM3      object
 14  SYMPTOM4      object
 15  SYMPTOM5      object
 16  VAX_TYPE      object
 17  VAX_MANU      object
dtypes: datetime64[ns](4), float64(2), int32(1), object(11)
memory usage: 312.2+ MB

In [63]:
vaers['VAERS_ID']=vaers.VAERS_ID.astype('int32')
vaers['RECVDATE']=pd.to_datetime(vaers['RECVDATE'])
vaers['DATEDIED']=pd.to_datetime(vaers['DATEDIED'])
vaers['VAX_DATE']=pd.to_datetime(vaers['VAX_DATE'])
vaers['ONSET_DATE']=pd.to_datetime(vaers['ONSET_DATE'])
vaers['NUMDAYS']=vaers.NUMDAYS.astype('float64')
vaers['AGE_YRS']=vaers.AGE_YRS.astype('float64')

In [64]:
vaers.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2212158 entries, 0 to 2212157
Data columns (total 18 columns):
 #   Column        Dtype
---  ------        -----
 0   VAERS_ID      int32
 1   RECVDATE      datetime64[ns]
 2   STATE         object
 3   AGE_YRS       float64
 4   SEX           object
 5   SYMPTOM_TEXT  object
 6   DIED          object
 7   DATEDIED      datetime64[ns]
 8   VAX_DATE      datetime64[ns]
 9   ONSET_DATE    datetime64[ns]
 10  NUMDAYS       float64
 11  SYMPTOM1      object
 12  SYMPTOM2      object
 13  SYMPTOM3      object
 14  SYMPTOM4      object
 15  SYMPTOM5      object
 16  VAX_TYPE      object
 17  VAX_MANU      object
dtypes: datetime64[ns](4), float64(2), int32(1), object(11)
memory usage: 312.2+ MB

In [65]:
vaers.head()

,VAERS_ID,RECVDATE,STATE,AGE_YRS,SEX,SYMPTOM_TEXT,DIED,DATEDIED,VAX_DATE,ONSET_DATE,NUMDAYS,SYMPTOM1,SYMPTOM2,SYMPTOM3,SYMPTOM4,SYMPTOM5,VAX_TYPE,VAX_MANU
0,25001,1990-07-02,WI,0.2,F,Loud intense cry with screaming for 1 1/2 hrs....,UKNOWN,1900-01-01,1990-06-04,1990-06-04,0.0,Agitation,NaN,NaN,NaN,NaN,DTP,CONNAUGHT LABORATORIES
1,25003,1990-07-02,TX,0.8,M,"Hypotonic, Hyporesponsive episode, Infant died...",Y,1900-01-01,1990-01-29,1990-02-04,6.0,Delirium,Hypokinesia,Hypotonia,NaN,NaN,DTP,LEDERLE LABORATORIES
2,25003,1990-07-02,TX,0.8,M,"Hypotonic, Hyporesponsive episode, Infant died...",Y,1900-01-01,1990-01-29,1990-02-04,6.0,Delirium,Hypokinesia,Hypotonia,NaN,NaN,OPV,PFIZER\WYETH
3,25004,1990-07-02,NY,0.9,M,"Pt developed chills for approx. 1 hr, felt ach...",UKNOWN,1900-01-01,1989-11-13,1989-11-13,0.0,Chills,Dermatitis contact,Oedema genital,Pelvic pain,NaN,OPV,PFIZER\WYETH
4,25005,1990-07-02,OK,0.0,U,7 patients within 2 weeks have reported joint ...,UKNOWN,1900-01-01,1900-01-01,1900-01-01,0.0,Arthritis,Injection site oedema,Injection site reaction,NaN,NaN,TD,LEDERLE LABORATORIES

In [84]:
covid=vaers[(vaers['RECVDATE']>='2020-01-01') & (vaers['VAX_TYPE']=='COVID19') & (vaers['VAX_DATE']!='1900-01-01')& (vaers['STATE']!='FR')]

In [86]:
dead=covid[covid.DIED=='Y']

In [104]:
print(dead.NUMDAYS.mean())
test=dead.groupby('SYMPTOM1').count()
test.sort_values('VAERS_ID',ascending=False).head(11)

38.969793322734496

,VAERS_ID,RECVDATE,STATE,AGE_YRS,SEX,SYMPTOM_TEXT,DIED,DATEDIED,VAX_DATE,ONSET_DATE,NUMDAYS,SYMPTOM2,SYMPTOM3,SYMPTOM4,SYMPTOM5,VAX_TYPE,VAX_MANU
SYMPTOM1,,,,,,,,,,,,,,,,,
Death,2361,2361,2361,2361,2361,2360,2361,2361,2361,2361,2361,991,589,386,251,2361,2361
COVID-19,367,367,367,367,367,367,367,367,367,367,367,363,332,208,156,367,367
Cardiac arrest,256,256,256,256,256,256,256,256,256,256,256,235,178,130,91,256,256
Asthenia,221,221,221,221,221,221,221,221,221,221,221,221,210,196,172,221,221
Acute kidney injury,157,157,157,157,157,157,157,157,157,157,157,153,127,106,93,157,157
Autopsy,149,149,149,149,149,149,149,149,149,149,149,149,115,81,63,149,149
Dyspnoea,102,102,102,102,102,102,102,102,102,102,102,93,85,71,55,102,102
Cerebrovascular accident,96,96,96,96,96,96,96,96,96,96,96,83,46,27,21,96,96
Acute respiratory failure,96,96,96,96,96,96,96,96,96,96,96,96,91,80,76,96,96
SARS-CoV-2 test positive,79,79,79,79,79,79,79,79,79,79,79,37,17,7,3,79,79
Abdominal pain,76,76,76,76,76,76,76,76,76,76,76,76,75,63,60,76,76